import pyray
import modules.map_utils as map_utils

BG_COLOR = pyray.Color(5, 10, 30, 255)

MAP_SIZE_X = 1000
MAP_SIZE_Y = 500

MIN_ZOOM = 0.5
MAX_ZOOM = 16.0

MOUSE_POS_CIRCLE_SIZE = 4
MOUSE_POS_CIRCLE_COLOR = pyray.DARKGRAY

SELECTED_POS_CIRCLE_SIZE = 5
SELECTED_POS_CIRCLE_COLOR = pyray.RED

LINE_COLOR = pyray.BLACK

MOUSE_POS_TEXT_POSITION = pyray.Vector2(-44, -24)
MOUSE_POS_TEXT_FONT_SIZE = 20
MOUSE_POS_TEXT_SPACING = 2
MOUSE_POS_TEXT_COLOR = pyray.BLACK

TIME_TEXT_FONT_SIZE = 70
TIME_TEXT_SPACING = 0
TIME_TEXT_COLOR = pyray.Color(195, 198, 188, 200)
