import pyray

BG_IMAGE = "resources/2d_art/Background.png"

TITLE_COLOR = pyray.Color(195, 198, 188, 255)
TITLE_FONT_SIZE = 70
TITLE_SPACING = 0

PLAY_BUTTON_TEXT_COLOR = pyray.Color(23, 47, 61, 255)
PLAY_BUTTON_TEXT_FONT_SIZE = 50
PLAY_BUTTON_TEXT_SPACING = 0
PLAY_BUTTON_PADDING_X = 15
PLAY_BUTTON_PADDING_Y = 10
PLAY_BUTTON_IMAGE = "resources/2d_art/Button.jpg"